"""Phase 6 deliverables that must not drift from the code that serves them.

`DISCLAIMER.md` and `SOURCES.md` are deliverables the reviewer reads alongside a
running app, which is exactly the condition under which a hand-written copy
quietly goes stale: the string in the file stops matching the string in
`config`, and nothing notices. So both are *generated* from the same constants
the app draws from, and `src/verify_phase6.py` fails if the committed file
disagrees with what this module would write today.

Run:

    .venv\\Scripts\\python.exe -m src.deliverables

`SOURCES.md` is generated from `src/sources.py`, the same registry the ingestion
pipeline fetches and the query path validates citations against, so the
delivered list is the ingested list by construction (PRD §9.8, SC-1).
"""

from __future__ import annotations

import sys

from src import config, sources, vectorstore
from src.config import PROJECT_ROOT

DISCLAIMER_MD: str = PROJECT_ROOT / "DISCLAIMER.md"
SOURCES_MD: str = PROJECT_ROOT / "SOURCES.md"


def disclaimer_markdown() -> str:
    """The disclaimer deliverable, quoting the exact string the UI shows.

    The wording is read from `config.DISCLAIMER` rather than typed here, so this
    file cannot claim a stronger or weaker promise than the app makes.
    """
    return (
        "# Disclaimer\n"
        "\n"
        "## The snippet used in the app\n"
        "\n"
        f"> {config.DISCLAIMER}\n"
        "\n"
        "That is the exact string the interface shows on load, taken from\n"
        "`config.DISCLAIMER` in `src/config.py`. It is a fixed constant, never\n"
        "generated by the language model.\n"
        "\n"
        "## What it means in practice\n"
        "\n"
        "The assistant answers published facts about the five HDFC Mutual Fund\n"
        "schemes named in `SOURCES.md`, and every factual answer carries one link\n"
        "to the page the fact was read from plus a `Last updated from sources:`\n"
        "line dated from when that page was fetched.\n"
        "\n"
        "It does not, and by design cannot:\n"
        "\n"
        "- recommend buying, selling, holding, or switching a scheme;\n"
        "- calculate, compare, rank, or quote returns or performance figures;\n"
        "- answer about a fund, AMC, or asset class outside the five sources;\n"
        "- accept, store, or echo personal identifiers such as PAN, Aadhaar,\n"
        "  account numbers, OTPs, email addresses, or phone numbers.\n"
        "\n"
        "Where a question needs a return figure, the app redirects to the\n"
        "official factsheet published by the AMC rather than producing a number.\n"
        "Where retrieval finds nothing relevant, it says the information is not\n"
        "in its sources instead of guessing.\n"
        "\n"
        "Nothing here is investment advice. Mutual fund investments are subject to\n"
        "market risks; read the scheme's own documents and speak to a registered\n"
        "mutual fund distributor before acting.\n"
    )


def sources_markdown() -> str:
    """The source-list deliverable, generated from the ingestion registry.

    The `fetched_at` column comes from the manifest rather than from the current
    clock, so the file records when the pages were actually read. A source that
    is in the registry but not yet in the manifest is still listed, marked as
    not ingested, because a registry entry and an ingested page are different
    facts and a reviewer checking SC-1 needs to see which is which.
    """
    manifest = vectorstore.read_manifest() or {}
    fetched_by_url = {
        row.get("source_url", ""): row.get("fetched_at", "")
        for row in manifest.get("sources", [])
    }

    lines: list[str] = []
    lines.append("# Sources")
    lines.append("")
    lines.append(
        "The complete list of pages this assistant may read and cite. Generated"
    )
    lines.append(
        "from the source registry in `src/sources.py` — the same registry the"
    )
    lines.append(
        "ingestion pipeline fetches from and the query path validates every"
    )
    lines.append("citation against. No page outside this list is ever ingested or")
    lines.append("cited (SC-1, SC-9, PRD §9.8).")
    lines.append("")
    lines.append(
        f"Registry size: {len(sources.SOURCES)}. "
        f"Chunks ingested: {manifest.get('chunk_count', 'not ingested')}."
    )
    lines.append("")
    lines.append("## AMC")
    lines.append("")
    lines.append("HDFC Mutual Fund (HDFC AMC), via the public fund-distributor")
    lines.append("pages below.")
    lines.append("")
    lines.append("## The five ingested pages")
    lines.append("")
    lines.append("| # | Scheme (as the page titles it) | Brief label | URL | Fetched |")
    lines.append("|---|---|---|---|---|")
    for number, source in enumerate(sources.SOURCES, start=1):
        fetched = fetched_by_url.get(source.source_url, "")
        if not fetched:
            fetched = "not ingested"
        lines.append(
            f"| {number} | {source.page_name} | {source.brief_label} | "
            f"<{source.source_url}> | {fetched} |"
        )
    lines.append("")
    lines.append("## Educational links shown with refusals")
    lines.append("")
    lines.append(
        "A refusal carries a fixed educational link instead of a source citation:"
    )
    lines.append(
        "the link is not evidence for a fact, so it never gets a `Last updated`"
    )
    lines.append("stamp. These are curated constants in `config.EDUCATIONAL_LINKS`,")
    lines.append("never model-written, and every host is on an allowlist.")
    lines.append("")
    lines.append("| Purpose | Link |")
    lines.append("|---|---|")
    for label, key in (
        ("Official factsheets", "factsheet"),
        ("Scheme details and risk disclosures", "scheme_details"),
        ("Regulator material on risk", "risk_and_regulation"),
        ("Investor education", "investor_education"),
        ("The corpus source pages", "source_pages"),
    ):
        lines.append(f"| {label} | <{config.EDUCATIONAL_LINKS[key]}> |")
    lines.append("")
    lines.append("## Not ingested, deliberately")
    lines.append("")
    lines.append("- Holdings tables, return calculators, historic-returns tickers,")
    lines.append("  returns-and-rankings tables, and similar-fund comparison blocks.")
    lines.append("  Performance and rankings are out of scope (PRD §4), and a")
    lines.append("  stale returns table in the corpus is a number the app could quote.")
    lines.append("- The live NAV. It changes daily and would contradict the")
    lines.append("  `Last updated from sources:` stamp within a day.")
    lines.append("- Distributor star ratings and category ranks (PRD §4).")
    lines.append("- Fund-manager card lists of other HDFC schemes, which name")
    lines.append("  schemes that are not in this corpus and invite citing one.")
    lines.append("- AMC and RTA contact details.")
    lines.append("- Third-party blogs, news sites, forums, and social media")
    lines.append("  (PRD §9.2), and any back-end screenshots (PRD §9.3).")
    lines.append("")
    lines.append("## Naming note")
    lines.append("")
    lines.append(
        "`HDFC Equity Fund` in the brief and the PRD is titled `HDFC Flexi Cap"
    )
    lines.append(
        " Direct Plan Growth` on the page served at that URL; the scheme was"
    )
    lines.append("renamed. Both names are recorded in the registry so the")
    lines.append(
        "discrepancy stays visible, and a question using the brief's name is"
    )
    lines.append(
        "rewritten to the corpus name at query time (`sources.SCHEME_ALIASES`)."
    )
    lines.append("")
    lines.append("## Regenerating this file")
    lines.append("")
    lines.append("```")
    lines.append(".venv\\Scripts\\python.exe -m src.deliverables")
    lines.append("```")
    lines.append("")
    return "\n".join(lines)


GENERATORS = {
    DISCLAIMER_MD: disclaimer_markdown,
    SOURCES_MD: sources_markdown,
}


def render_all() -> dict[str, str]:
    """Return {path: content} for every generated deliverable, writing nothing."""
    return {path: builder() for path, builder in GENERATORS.items()}


def write_all() -> list[str]:
    """Write every generated deliverable. Returns the paths written."""
    written: list[str] = []
    for path, content in render_all().items():
        path.write_text(content, encoding="utf-8")
        written.append(str(path))
        print(f"wrote {path} ({path.stat().st_size:,} bytes)")
    return written


def stale_deliverables() -> list[tuple[str, str]]:
    """Return [(path, reason)] for every deliverable that is missing or stale.

    A committed file is stale when its bytes differ from what the generator
    produces today. This is the check that makes the files reviewable without
    making them hand-maintained.
    """
    problems: list[tuple[str, str]] = []
    for path, builder in GENERATORS.items():
        expected = builder()
        if not path.exists():
            problems.append((str(path), "missing; run python -m src.deliverables"))
            continue
        actual = path.read_text(encoding="utf-8")
        if actual != expected:
            problems.append(
                (
                    str(path),
                    "stale; it no longer matches the constants in src/ "
                    "(run python -m src.deliverables)",
                )
            )
    return problems


def main(argv: list[str] | None = None) -> int:
    del argv
    print("Phase 6 generated deliverables")
    print("-----------------------------")
    write_all()
    problems = stale_deliverables()
    if problems:
        print("\nstill stale after writing:")
        for path, reason in problems:
            print(f"  - {path}: {reason}")
        return 1
    print("\nAll generated deliverables are current.")
    return 0


__all__ = [
    "DISCLAIMER_MD",
    "SOURCES_MD",
    "disclaimer_markdown",
    "main",
    "render_all",
    "sources_markdown",
    "stale_deliverables",
    "write_all",
]


if __name__ == "__main__":
    sys.exit(main())
